import Head from 'next/head'

export interface LayoutInterface {
	title: string
	children: JSX.Element
}

const MainLayout: React.FC<LayoutInterface> = ({ children, title }) => {
	return (
		<>
			<Head>
				<title>{ title || 'Next Application' }</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className='mainlayout'>
				{ children }
			</main>
		</>
	);
};

export default MainLayout;

